---
- name: Include user setup tasks
  ansible.builtin.include_tasks: user.yml
- name: Include Docker setup tasks
  ansible.builtin.include_tasks: docker.yml
- name: Include deployment tasks
  ansible.builtin.include_tasks: deploy.yml
